<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDriven_PD1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e902657c-e459-4b19-9d9b-652f0d4672cd</testSuiteGuid>
   <testCaseLink>
      <guid>dbcdaf4f-053e-4c08-90d8-e79b304947b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Info TCs/PersonalDetails/DataDriven_PD1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d71df70c-5f1c-414a-969c-c4d68b57bd57</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/PD1</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d71df70c-5f1c-414a-969c-c4d68b57bd57</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>firstName</value>
         <variableId>9643d65f-6743-4345-9913-bf06c351ea1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d71df70c-5f1c-414a-969c-c4d68b57bd57</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>middleName</value>
         <variableId>b86c9ee4-d95a-41c6-904e-43ceb21c3b77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d71df70c-5f1c-414a-969c-c4d68b57bd57</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastName</value>
         <variableId>df3a123c-234c-4143-a1f5-6c0f5a55634b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
