<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LeftMenu_Expanded</name>
   <tag></tag>
   <elementGuidId>59ecc370-256a-4899-a928-555fe731e00b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;oxd-main-menu-item&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>2ce288c2-108b-4d07-9eb4-078bc6cbd222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1720718835653</value>
      <webElementGuid>3c1ba251-9621-4d8c-960b-b7a6161a4457</webElementGuid>
   </webElementProperties>
</WebElementEntity>
