<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ContactDetails</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>30ce5194-b64e-4504-8b3f-ef33865d12a4</testSuiteGuid>
   <testCaseLink>
      <guid>1c3492f3-7ac4-4640-86e7-bbfb5207fe27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Info TCs/ContactDetails/AddContactDetails1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af9e1d1f-8ceb-4cba-8a8f-327fa57cf8c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3d7f516-f2f5-4a86-a46d-d6fd5024123a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c367f37f-8e1c-48d5-bee1-7b3712039417</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eacecb07-894a-498d-9143-54af1ede82f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d707a886-ac16-4ffb-9947-694c9d7daab5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86cdcc51-5146-41a0-a7ff-80145fea3d52</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c42c25ce-fc77-4260-90a5-cc6a3346f29f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Info TCs/ContactDetails/AddContactDetails2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e55013df-18fb-4399-bd7e-2cb928b17a6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7993039e-9cda-485d-8336-6a67fa774127</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3acc76d7-d84e-4e91-88fe-218b68864ffc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9df5251-f225-4651-b7f8-3f07dc512edd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Info TCs/ContactDetails/AddContactDetails3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3461bcc7-775e-4759-b6db-493cb9f97b66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21b72278-5494-4740-8ba5-7e463697d6ab</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
